### ISSUE TITLE
手指松开后 还会继续滑动

### ISSUE THREAD

**Issue by tu0908** [angcyo/LoopRecyclerView#1]
当item的宽度没有占满屏幕时 手指松开后 还会继续滑动

**Comment by dengxingwen** [comment]
同样的问题

**Comment by wusir-china** [comment]
怎样把轮播的时间提取出来，目前写死了轮播时间

**Comment by angcyo** [comment]
核心`LayoutManager`库 https://github.com/leochuan/ViewPagerLayoutManager

我在此作者库上修改了, 常见问题. 

https://github.com/angcyo/ViewPagerLayoutManager
