### ISSUE TITLE
滑动获取到的位置不对

### ISSUE THREAD

**Issue by looooker** [angcyo/LoopRecyclerView#4]
滑动之后，获取当前item位置不对

**Comment by looooker** [comment]
向上滑动位置为0，或者无穷大。
 //滑动监听
        mLoopRecyclerView.addOnScrollListener(new RecyclerView.OnScrollListener() {
            @Override
            public void onScrollStateChanged(@NonNull RecyclerView recyclerView, int newState) {
                super.onScrollStateChanged(recyclerView, newState);
                if (recyclerView != null && recyclerView.getChildCount() > 0) {
                    try {

                        int currentPositionPage = ((LinearLayoutManager) recyclerView.getLayoutManager()).findFirstVisibleItemPosition();
//                        int currentPositionPage = ((RecyclerView.LayoutParams) recyclerView.getChildAt(0).getLayoutParams()).getViewAdapterPosition();
                        Log.e("TanluSlideAdapter", "fragment currentPositionPage = " + currentPositionPage + " >>> size = " + markerExploreWayList.size() + " >>mCurrentPosition = " + mCurrentPosition);
                        if (currentPositionPage >= markerExploreWayList.size()) {
                            return;
                        }

                        if (mCurrentPosition != currentPositionPage) {
                            mCurrentPosition = currentPositionPage;
                            Log.d("TanluSlideAdapter", "-----fragment-------mCurrentPosition = " + mCurrentPosition);
                            moveMapLocation(mCurrentPosition);
                        }
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            }

            @Override
            public void onScrolled(@NonNull RecyclerView recyclerView, int dx, int dy) {
                super.onScrolled(recyclerView, dx, dy);
            }
        });

**Comment by angcyo** [comment]
使用`com.leochuan.ViewPagerLayoutManager#getCurrentPosition` 方法获取当前的位置.

**Comment by 12345nbaa** [comment]
if (mLoopRecyclerView.getLoopLayoutManager() == null) {
                            return;
                        }
                        int currentPositionPage = mLoopRecyclerView.getLoopLayoutManager().getCurrentPosition();
                        Log.e(TAG, "fragment currentPositionPage = " + currentPositionPage + " >>> size = " + markerExploreWayList.size() + " >>mCurrentPosition = " + mCurrentPosition);
                

日志：
03-20 12:16:19.970 9515-9515/com.mogo.launcher E/TanluCardViewFragment: fragment currentPositionPage = 2147483645 >>> size = 10 >>mCurrentPosition = 0
03-20 12:16:20.510 9515-9515/com.mogo.launcher E/TanluCardViewFragment: fragment currentPositionPage = 2147483644 >>> size = 10 >>mCurrentPosition = 0
03-20 12:16:23.780 9515-9515/com.mogo.launcher D/TanluCardViewFragment: mogoVoiceListener  cmd = com.zhidao.tanlu.play
03-20 12:16:36.830 9515-9515/com.mogo.launcher D/TanluCardViewFragment:  onButtonUpAndDown event.type =1
03-20 12:16:36.830 9515-9515/com.mogo.launcher E/TanluCardViewFragment: fragment currentPositionPage = 2147483644 >>> size = 10 >>mCurrentPosition = 0
03-20 12:16:37.350 9515-9515/com.mogo.launcher E/TanluCardViewFragment: fragment currentPositionPage = 2147483643 >>> size = 10 >>mCurrentPosition = 0

这个方法也不行，向上滑动正确，向下滑动值是2147483645，不是size的值

**Comment by angcyo** [comment]
参考这个库: #1

**Comment by 12345nbaa** [comment]
这个库，会造成anr，类似死循环

**Comment by angcyo** [comment]
> 这个库，会造成anr，类似死循环

用我修改过的库. 
https://github.com/angcyo/ViewPagerLayoutManager
